name: exo5 - installer node

on:
  workflow_dispatch:
  
jobs:
  install-and-check:
    runs-on: ubuntu-latest

    steps:
    - name: Installer Node.js 18
      uses: actions/setup-node@v6.1.0
      with:
        node-version: 18

    - name: afficher version
      run: node -v
