name: exo5 - installer node

on:
  workflow_dispatch:
  
jobs:
  node-ubuntu-matrix:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        node-version: [16, 18, 20]

    steps:
    - name: Installer Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v6.1.0
      with:
        node-version: ${{matrix.node-version}}

    - name: afficher version
      run: |
        echo "OS : ${{matrix.node-version}}
        node -v
        npm -v
